### ISSUE TITLE
large(ish) redis dump.rdb not handled gracefully by health check

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-docker-compose#10]
The lis edition of the dump file is currently ~400MB; small by genomic standards, but apparently large enough that it takes the redisearch service longer than 90s to read it fully and proclaim itself ready for business. The current config of the compose file uses the defaults for the health check options, which are 

> --interval=DURATION (default: 30s)
> --timeout=DURATION (default: 30s)
> --start-period=DURATION (default: 0s)
> --retries=N (default: 3)

this causes the healthcheck to fail and other services to not be started. I tweaked the options in the compose file to get around this, but I can imagine it being a pain point for users not forced to figure out what was going on like I finally did. Is there a better way of dealing with variable length startup times?

**Comment by nathanweeks** [comment]
Setting reasonable healthcheck values in the compose file that works for more use cases seems like a good way of dealing with this. Might at least bump up the number of retries to 6 (or more?).

**Comment by adf-ncgr** [comment]
Thanks @nathanweeks I think that seems reasonable as well; I don't have a sense for what the possible downsides are but I guess it would all be in the nature of having to wait longer to give up when there was a real issue causing "unhealth"?

**Comment by alancleary** [comment]
Thanks for bringing this up @adf-ncgr. I've actually suffered these slow Redis start times on my development machine for quite some time. I never bothered to dig into it, though, because no one else seemed to have the issue!

It turns out I just need to increase the start period for it to load without failing:
```
diff --git a/compose.yml b/compose.yml
index 6fb4fec..bcbe702 100644
--- a/compose.yml
+++ b/compose.yml
@@ -39,6 +39,7 @@ services:
     image: redislabs/redisearch:2.4.14
     healthcheck:
       test: "redis-cli ping | grep -q PONG"
+      start_period: 120s
     expose:
       - "6379"
     volumes:
```

**Comment by nathanweeks** [comment]
> Thanks for bringing this up @adf-ncgr. I've actually suffered these slow Redis start times on my development machine for quite some time. I never bothered to dig into it, though, because no one else seemed to have the issue!

I'm guessing you're using Docker Desktop for Mac? If so, have you tried enabling [virtiofs](https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/)?

**Comment by alancleary** [comment]
> I'm guessing you're using Docker Desktop for Mac? If so, have you tried enabling [virtiofs](https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/)?

@adf-ncgr uses mac, although I suspect he uses the Docker CLI. I use the CLI on Arch Linux. Did I mention in use Arch Linux?

**Comment by adf-ncgr** [comment]
@alancleary why do I feel slightly ashamed when you say that I'm using Mac? 
I was actually running into problems when trying to deploy the release-tagged images on my Mac; but this appeared to have been due to incompatibility of ARM-based docker hosts (ie apple M1) with the x86-based images that are packaged (in particular, my redis was core-dumping when trying to load stuff). I don't think this would have been an issue doing development, though, as the builds then are done locally and [directives to use Rosetta emulation](https://docs.docker.com/desktop/mac/apple-silicon/#known-issues) then would have been respected (at least I think I've done this in the past and it's been OK). And I'm not planning to use my Mac as a hosting platform anytime soon so I decided it wasn't worth reporting (although it was an interesting test case for the "health check"- after I tweaked the params there I thought I was waiting a long time because the of the db but it was really because it was quite unhealthy but doing its best to ignore it!)

**Comment by alancleary** [comment]
OK, so regarding this issue do we want to add `start_period: ${REDIS_START_PERIOD:-90s}` to the redisearch service's `healthcheck` attribute, as I previously described?

Regarding Apple M1, it looks like the official redisearch image doesn't support arm64 (i.e. mac m1) so for now we could update the compose files to specify `platform: linux/amd64` for redisearch and all of the prebuilt GCV images and mention in the readme this requires mac m1 users to install rosetta 2 so they can correctly emulate the amd64 architecture. It's probably worth opening an issue to update our builds to also generate apple m1 compatible images, but I don't think it should be a priority until redisearch supports m1.

**Comment by adf-ncgr** [comment]
Yes, I think adding the healthcheck configuration via your suggestion is a good approach.
I agree that support for apple M1 is not a priority.

**Comment by alancleary** [comment]
Done in commit 2a29658c9378bac135aacba732ecae48ea803071. Closing.
