### ISSUE TITLE
Traefik zone and COMPOSE_PROJECT_NAME

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv-docker-compose#5]
@adf I can't get the [`microservices/compose.prod.yml`](https://github.com/legumeinfo/gcv/blob/main/microservices/compose.prod.yml) file to work with the `traefik.zone=${COMPOSE_PROJECT_NAME}` lines you added. I found [the commit](https://github.com/legumeinfo/microservices/commit/d0762f1ce8ad67aa8d7d75646d20b170a78619bd) where you added the lines and read the corresponding forum discussion and documentation. However, it doesn't work even if I just replace the `COMPOSE_PROJECT_NAME` environment variable with a hard-code value. Can you explain how you're using this?

**Comment by alancleary** [comment]
Looks like I forgot to set the `REV_PROXY_PORT` environment variable. Whoops! It's now working with a hard-coded value.

I'm still curious how you're using the `COMPOSE_PROJECT_NAME` variable since it doesn't have a docker assigned value (default or via the `--project` flag) when the compose file is parsed.

**Comment by adf-ncgr** [comment]
Whew, I was just starting to dig into that nearly 1 year old commit to see if I could remember anything about it (though my comment suggests that you were the real brain behind the change). I am just setting the value in the .env file, e.g.:
COMPOSE_PROJECT_NAME=glycine
let me know if that doesn't answer your question

**Comment by alancleary** [comment]
OK. Thanks for clarifying. Setting the `COMPOSE_PROJECT_NAME` variable via the `.env` file works. I guess the issues I'm having must be related to how I'm breaking the docker compose config into multiple files: base, dev, and prod.

**Comment by adf-ncgr** [comment]
premature modularization is the root of some evil
