### ISSUE TITLE
Provide example database

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv-docker-compose#6]
We should provide a small example database with the gcv-docker-compose repo so users can verify that they've gotten everything up and running correctly before attempting to load their own data.

**Comment by nathanweeks** [comment]
Alternatively, example GFF & GFA files could be provided, as well as an example loader script that is run by the redis_loader service's [entrypoint.sh](https://github.com/legumeinfo/microservices/blob/main/redis_loader/entrypoint.sh) script.

**Comment by alancleary** [comment]
Now that you mention it, we should probably provide both. The preloaded database would let the user verify that GCV and the microservices are set up correctly, and the example GFF/GFA and loading script would show them how to get their data into GCV.

Now that I think about it, all of this should probably be done directly in the microservices repo so that the files can also serve as testing data. Then I could finally get legumeinfo/gcv#374 underway!

**Comment by CFGrote** [comment]
Same here. We're keen at running GCV2 for analysing some closely related bacterial genomes.
After successfully bringing up the web-app I'm at loss how to get any data in. I tried with the following loader script  microservices/redis_loader/docker-entrypoint-initdb.d/example.sh:

``` 
!/bin/sh

set -o errexit -o pipefail

wget -O - https://data.legumeinfo.org/Medicago/truncatula/genomes/R108_HM340.gnm1.XT6J/medtr.R108_HM340.gnm1.XT6J.genome_main.fna.gz.fai |
  awk ' BEGIN { FS=OFS="\t"; print "##gff-version 3" }
        { 
            print $1, ".", $1 ~ /\.scf/ ? "supercontig" : "chromosome", 
                   1, $2, ".", ".", ".", "ID=" $1 ";" "Name=" $1 
        }' > chromosome.gff3
wget -O genes.gff3.gz https://data.legumeinfo.org/Medicago/truncatula/annotations/R108_HM340.gnm1.ann1.85YW/medtr.R108_HM340.gnm1.ann1.85YW.gcv_genes.gff3.gz

wget -O gfa.tsv.gz https://data.legumeinfo.org/Medicago/truncatula/annotations/R108_HM340.gnm1.ann1.85YW/medtr.R108_HM340.gnm1.ann1.85YW.legfed_v1_0.M65K.gfa.tsv.gz

python -u -m redis_loader --load-type append gff \
       --genus Medicago \
       --species truncatula \
       --strain R108_HM340 \
       --gene-gff genes.gff3.gz
       --gfa gfa.tsv.gz
       --chromosome-gff chromosome.gff3
```

Then I start the server and client with
```
docker-compose -f compose.yml -f compose.prod.yml --profile all up -d
```

and finaly
```
docker-compose -f compose.yml -f compose.prod.yml run redis_loader
```

which produces the following output
```
Creating gcv_redis_loader_run ... done
/app
```
The web app (after reloading) still shows no data as in OP's screenshot.

I tried to follow the instructions in the wiki as good as I could, but obviously got it all wrong. Any help would be appreciated.

**Comment by adf-ncgr** [comment]
@CFGrote great to hear that you are trying to use GCV2- I have a small howto written up that got stalled en route to addressing https://github.com/legumeinfo/microservices/issues/601 but this motivates me to get that finally committed- hopefully today or tomorrow....

**Comment by CFGrote** [comment]
great, looking forward to see your howto.

thanks for getting back so quickly!

**Comment by adf-ncgr** [comment]
closing this but feel free to reopen if anyone on the thread feels what @alancleary and I put into place is insufficiently exemplar

**Comment by alancleary** [comment]
@CFGrote A new release has been tagged (`v2.6.0-c1`) that updates the documentation as well as the behavior of the redis_loader microservice. Hopefully this will be adequate for your purposes. Let us know if you're still having trouble!
